### PR TITLE
Moriarty Hand & Weekend Update

### PR DESCRIPTION
**Pull request by mapsam**
TWO new linesets for Project Linework! This is some pretty incredible work by @dylanmoriarty and @jonahadkins. New additions also include `topojson` files quantized at `1e5` ([thank goodness for this post](http://www.projectlinework.org/2013/10/07/topojson_files.html)) in order to prevent any weird looking edges or jagged lines. Below are the new sets:

# [Weekend Update](https://github.com/mapsam/project-linework/tree/moriarty-weekend-update/linework-sets/weekend-update)

*Author @jonahadkins from the classic SNL weekend update backdrop. Excellent job, good sir! Files and types are below.*

**Land**, **Lines**, and **Polygons**

weekend-update

# [Moriarty Hand](https://github.com/mapsam/project-linework/tree/moriarty-weekend-update/linework-sets/moriarty-hand)

*Author: @dylanmoriarty puts together some excellent hand-drawn vector work that covers the globe. Impressive!*

**Admin_0_Lines**, **Admin_0_Polygons**, **Admin_1_Lines**, **Admin_1_Polygons**, **Land**, **Rivers**, and **Waterbodies**

dance-oh-yeah
---

Please give everything a look over and send your descriptions for the website via github issues! @pinakographos going to wait on your thumbs up before running `build.js` and pushing to s3. Will work on website updates this weekend so we can get these out next week!

### CODE REVIEW

**Comment by pinakographos** [comment]
Moriarty Hand is a global, hand drawn set of vector linework covering the world's countries, major rivers and lakes, and US states & Canadian provinces. It was created by tracing bits and pieces of Natural Earth linework, then filling in the rest by eyeballing a reference map, which makes it both accurate enough to use and inaccurate enough to look human-made. 

Author: Dylan Moriarty

Coverage: Worldwide. Coastline | Admin 0 (countries) | Admin-1 (states/provinces) for USA & CAN | Major lakes | Major rivers

Version: 1.0

---------

Based on the iconic background from the 'Weekend Update' segments on Saturday Night Live over the years. This hand drawn, Mercator version styles the United States and European countries with simplified lines made popular during the Tina Fey, Amy Poehler, and Jimmy Fallon years.

Author: Jonah Adkins

Coverage: Admin 0 (countries) for Europe (excludes Russia, Asian Turkey, and some smaller nations), and the continental USA | Admin-1 (states) for continental USA

Version: 1.0

**Comment by pinakographos** [comment]
I think everything looks good!

**Comment by DylanMoriarty** [comment]
All good here!

Cheers,
-Dylan

On Sat, Aug 29, 2015 at 10:18 AM, pinakographos <notifications@github.com>
wrote:

> I think everything looks good!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mapsam/project-linework/pull/16#issuecomment-135998486>
> .
>



-- 
dylanmoriarty.github.io
608.520.1259

**Comment by jonahadkins** [comment]
Looks Splendid :100:

**Comment by mapsam** [comment]
Excellent! Merging into `master` and will update `gh-pages` with the new information so we can tweet on Monday.

**Pull request merged**
