### PR TITLE
Updated styles

### PR DESCRIPTION
**Pull request by mapsam**
Updating styles for the website with newly added linework. @pinakographos what do you think?

screen shot 2015-08-29 at 1 30 19 pm

### CODE REVIEW

**Comment by mapsam** [comment]
screen shot 2015-08-29 at 4 00 22 pm

**Comment by pinakographos** [comment]
Looking great! Thanks for doing this! It's a nice surprise to have, to
celebrate our expansion.

**Comment by mapsam** [comment]
Also used @dylanmoriarty's very own linework for the background. Imported into QGIS like a charm!

**Comment by mapsam** [comment]
Website updates are ready to go! Including new Moriarty Hand & Weekend Update.

**Comment by DylanMoriarty** [comment]
Thanks so for doing this Sam! Looks great.

**Pull request merged**
